site_name: NeuroFlow
site_url: https://neurocog-mobility.github.io/neuroflow/
repo_url: https://github.com/neurocog-mobility/neuroflow

theme:
  name: "readthedocs"

nav:
  - Home: index.md
  - Setup:
    - Installation: setup/install.md
    - Useful Info: setup/useful-info.md
  - Tutorials:
    - Overview: tutorials/index.md 
    - GUI:
      - Pre-process:
        - tutorials/gui/pre-convert.md
        - tutorials/gui/pre-sync.md
        - tutorials/gui/pre-window.md
      - Event detection:
        - tutorials/gui/event-gait.md
        - tutorials/gui/event-ecg.md
        - tutorials/gui/event-validate.md
      - Feature extraction:
        - tutorials/gui/feature-metrics.md
  - Reference:
    - Analysis: analysis.md
    - API: api.md

markdown_extensions:
  - admonition

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - neuroflow
          options:
            docstring_style: google
            show_source: true